// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI7eJDnGcL8OKgtu81FocXLgkJmpdm9gQ',
    appId: '1:1074144160794:web:df758bc9dd53e469bdf5a3',
    messagingSenderId: '1074144160794',
    projectId: 'ams-up-fcm',
    authDomain: 'ams-up-fcm.firebaseapp.com',
    storageBucket: 'ams-up-fcm.firebasestorage.app',
    measurementId: 'G-LMFH8Z42J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5N4shHfEDHqiH_9xlTYPDkBKgGoN0FQ',
    appId: '1:1074144160794:android:c2538bea1e6d8510bdf5a3',
    messagingSenderId: '1074144160794',
    projectId: 'ams-up-fcm',
    storageBucket: 'ams-up-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Tu4VElub7NDH8gMiFpi0Of8MQoL8Rvw',
    appId: '1:1074144160794:ios:73a2c8f8c164149fbdf5a3',
    messagingSenderId: '1074144160794',
    projectId: 'ams-up-fcm',
    storageBucket: 'ams-up-fcm.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Tu4VElub7NDH8gMiFpi0Of8MQoL8Rvw',
    appId: '1:1074144160794:ios:73a2c8f8c164149fbdf5a3',
    messagingSenderId: '1074144160794',
    projectId: 'ams-up-fcm',
    storageBucket: 'ams-up-fcm.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI7eJDnGcL8OKgtu81FocXLgkJmpdm9gQ',
    appId: '1:1074144160794:web:945ccf9a14a2d3f5bdf5a3',
    messagingSenderId: '1074144160794',
    projectId: 'ams-up-fcm',
    authDomain: 'ams-up-fcm.firebaseapp.com',
    storageBucket: 'ams-up-fcm.firebasestorage.app',
    measurementId: 'G-MB4R63KPVJ',
  );
}
